apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameFile }}
data:
  nginx.conf: |
    events {}

    http {
      upstream backend {
        server todo;
      }

      server {
        listen 80 default_server;
        include /etc/nginx/mime.types;
        root /usr/share/nginx/html;
        try_files $uri $uri/;

        location / {
            proxy_pass http://backend;
            add_header  X-container-name backend;
            proxy_redirect     off;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
        }

        location /static/  {
            add_header  X-container-name frontend;
            try_files $uri $uri/;
        }
      }
    }