apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameFile }}
data:
  PORT: {{ .Values.container.port | quote }}
  DEBUG: {{ .Values.configMap.debug | quote }}
  HOST: {{ .Values.configMap.host | quote }}
  DBNAME: {{ .Values.configMap.dbName | quote }}
  FLASK_ENV: {{ .Values.configMap.flask_env | quote }}
  APP_VERSION: {{ .Values.configMap.app_version | quote }}