apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameFile }}
data:
  PORT: {{ .Values.container.port | quote }}
  DEBUG: "false"
  HOST: "0.0.0.0"
  DBNAME: todos
  FLASK_ENV: production
  APP_VERSION: {{ .Values.image.tag | quote }}