apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Looty/todo-list-charts.git
    targetRevision: HEAD
    path: todo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false